AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Places API

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Configuration"
        Parameters:
          - HereAppId
          - HereAppCode
          - HereBaseURL
Parameters:
  HereAppId:
    Type: String
    Description: App id for Here API
  HereAppCode:
    Type: String
    Description: App code for Here API
  HereAppCode:
    Type: String
    Description: 'Here API url up to the version number (Ex: https://places.demo.api.here.com/places/v1)'
    
Resources:

  #
  # Our Lambda function.  Basic code has been added.  You will replace the code later via your Github repo.
  #
  ContactUsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: places.handler
      Timeout: 5
      CodeUri: ./places.js
      Runtime: nodejs12
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /places
            Method: get
      Environment:
        Variables:
          HereAppId: !Ref HereAppId
          HereAppCode: !Ref HereAppCode
          HereBaseURL: !Ref HereBaseURL

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ServerlessRestApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod